config/routes.rb
Demo::Application.routes.draw do
  resources :dells

  resources :users

end

app/models/dell.rb
class Dell < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dells_controller.rb
class DellsController < ApplicationController
  # GET /dells
  # GET /dells.json
  def index
    @dells = Dell.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dells }
    end
  end

  # GET /dells/1
  # GET /dells/1.json
  def show
    @dell = Dell.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dell }
    end
  end

  # GET /dells/new
  # GET /dells/new.json
  def new
    @dell = Dell.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dell }
    end
  end

  # GET /dells/1/edit
  def edit
    @dell = Dell.find(params[:id])
  end

  # POST /dells
  # POST /dells.json
  def create
    @dell = Dell.new(params[:dell])

    respond_to do |format|
      if @dell.save
        format.html { redirect_to @dell, notice: 'Dell was successfully created.' }
        format.json { render json: @dell, status: :created, location: @dell }
      else
        format.html { render action: "new" }
        format.json { render json: @dell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dells/1
  # PUT /dells/1.json
  def update
    @dell = Dell.find(params[:id])

    respond_to do |format|
      if @dell.update_attributes(params[:dell])
        format.html { redirect_to @dell, notice: 'Dell was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dells/1
  # DELETE /dells/1.json
  def destroy
    @dell = Dell.find(params[:id])
    @dell.destroy

    respond_to do |format|
      format.html { redirect_to dells_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dells_helper.rb
module DellsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dells/_form.html.erb
<%= form_for(@dell) do |f| %>
  <% if @dell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dell.errors.count, "error") %> prohibited this dell from being saved:</h2>

      <ul>
      <% @dell.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first %><br />
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :second %><br />
    <%= f.text_field :second %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dells/edit.html.erb
<h1>Editing dell</h1>

<%= render 'form' %>

<%= link_to 'Show', @dell %> |
<%= link_to 'Back', dells_path %>

app/views/dells/index.html.erb
<h1>Listing dells</h1>

<table>
  <tr>
    <th>First</th>
    <th>Second</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dells.each do |dell| %>
  <tr>
    <td><%= dell.first %></td>
    <td><%= dell.second %></td>
    <td><%= link_to 'Show', dell %></td>
    <td><%= link_to 'Edit', edit_dell_path(dell) %></td>
    <td><%= link_to 'Destroy', dell, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dell', new_dell_path %>

app/views/dells/new.html.erb
<h1>New dell</h1>

<%= render 'form' %>

<%= link_to 'Back', dells_path %>

app/views/dells/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First:</b>
  <%= @dell.first %>
</p>

<p>
  <b>Second:</b>
  <%= @dell.second %>
</p>


<%= link_to 'Edit', edit_dell_path(@dell) %> |
<%= link_to 'Back', dells_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.number_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.phone %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @user.phone %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>